[package]
name = "rdns"
version = "0.1.0"
authors = ["Vinayak Goyal <vinayk@purelydysfunctional.com>"]
edition = "2024"
rust-version = "1.91"

[dependencies]
chrono = "0.4.43"
clap = { version = "4.5.54", features = ["derive"] }
crossterm = "0.29.0"
prometheus = "0.13"
ratatui = "0.30.0"
reqwest = { version = "0.13", features = ["json"] }
sysinfo = "0.38.0"
tokio = { version = "1.49.0", features = ["full"] }
warp = "0.3"
